version: "3.8"
networks:
  digital-twin-service:
x-ros-config: &ros-config
    - ROS_MASTER_URI=http://master:11311
services:
  master:
    image: niryo-ros-master:latest
    build: ../../../digital-twin-service/ros-master/
    environment: *ros-config
    ports:
     - 11311:11311
    networks:
     - digital-twin-service
  drivers:
    image: niryo-sim-drivers:latest
    build: ../../../digital-twin-service/niryo-one-drivers/simulation/
    environment: *ros-config
    depends_on:
      - master
    networks:
      - digital-twin-service
  robot-stack:
    image: niryo-one-full-stack:latest
    build: ../../../digital-twin-service/niryo-one-stack/niryo-one-stack/
    environment: *ros-config
    depends_on:
      - master
      - drivers
    networks: 
     - digital-twin-service
  dtwin:
    image: niryo-one-dtwin:latest
    build: ../../../digital-twin-service/digital-replica/
    environment: *ros-config
    depends_on:
      - master
      - drivers
      - robot-stack
    ports:
      - 19999:19999
    networks:
      - digital-twin-service
  web:
    image: niryo-one-web:latest
    build: ../../../digital-twin-service/web-interface/
    environment: *ros-config
    depends_on:
      - master
      - drivers
      - robot-stack
    networks:
     - digital-twin-service
  zenoh:
    image: eclipse/zenoh:0.5.0-beta.5
    ports:
      - 7447:7447
      - 7447:7447/udp
      - 8000:8000/tcp
    environment: 
      - RUST_LOG=debug
    networks:
     - digital-twin-service
  replay:
    image: zenoh-replay:latest
    build: ../../../digital-twin-service/replay-feature/
    environment:
      - ZENOH_ROUTER_ADDRESS=tcp/zenoh:7447
      - ROS_MASTER_URI=http://master:11311
      - REPLICA_ROS_TOPIC= /replay/joint_states 
      - REPLICA_HZ=15
      - REPLAY_DURATION=25  
    ports:
      - 5000:5000
    depends_on:
      - dtwin
    networks:
      - digital-twin-service
  test:
    image: ubuntu:latest
    command: sleep infinity
    networks:
      - digital-twin-service

